title: Brag Sheet - Sophia Dhrolia
author: Sophia Dhrolia
email: sdhrolia@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  This website contains an overview of some of my most important high school accomplishments and activities
# social links
twitter_username: sdhrolia # DO NOT include the @ character, or else the build will fail!
github_username:  sdhrolia # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-cayman
